---
- name: Cleanup installed services and containers
  hosts: webservers
  become: yes
  
  vars:
    # Global variables
    ephemeral_volume_path: "/tmp/ephemeral-data"
    
    # Docker variables
    docker_container_name: "uptime-kuma"
    docker_image: "louislam/uptime-kuma:latest"
    docker_network_name: "web-network"
    
  pre_tasks:
    - name: Display cleanup information
      debug:
        msg: |
          ========================================
          Starting Cleanup Process
          ========================================
          Target Server: {{ inventory_hostname }}
          Services to remove: Docker, MySQL, Apache2
          Ephemeral Storage: {{ ephemeral_volume_path }}
          Container to remove: {{ docker_container_name }}
          ========================================

  tasks:
    - name: Stop and remove Docker container
      docker_container:
        name: "{{ docker_container_name }}"
        state: absent
        force_kill: yes

    - name: Remove Docker image
      docker_image:
        name: "{{ docker_image }}"
        state: absent

    - name: Remove Docker network
      docker_network:
        name: "{{ docker_network_name }}"
        state: absent

    - name: Remove ephemeral storage directory
      file:
        path: "{{ ephemeral_volume_path }}"
        state: absent

    - name: Stop and disable Docker service
      service:
        name: docker
        state: stopped
        enabled: no

    - name: Remove Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: absent
        purge: yes
        autoremove: yes

    - name: Remove Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: absent

    - name: Remove Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: absent

    - name: Stop and disable MySQL service
      service:
        name: mysql
        state: stopped
        enabled: no

    - name: Remove MySQL packages
      apt:
        name:
          - mysql-server
          - mysql-client
          - python3-mysqldb
        state: absent
        purge: yes
        autoremove: yes

    - name: Remove MySQL data directory
      file:
        path: /var/lib/mysql
        state: absent

    - name: Remove MySQL configuration
      file:
        path: /etc/mysql/conf.d/custom.cnf
        state: absent

    - name: Stop and disable Apache2 service
      service:
        name: apache2
        state: stopped
        enabled: no

    - name: Remove Apache2 packages
      apt:
        name: apache2
        state: absent
        purge: yes
        autoremove: yes

    - name: Remove Apache2 configuration
      file:
        path: /etc/apache2
        state: absent

    - name: Remove Apache2 logs
      file:
        path: /var/log/apache2
        state: absent

    - name: Remove Apache2 web root
      file:
        path: /var/www
        state: absent

    - name: Clean up apt cache
      apt:
        autoclean: yes
        autoremove: yes

  post_tasks:
    - name: Display cleanup summary
      debug:
        msg: |
          ========================================
          Cleanup Summary
          ========================================
          ✅ Docker: Removed container, image, and packages
          ✅ MySQL: Removed packages and data
          ✅ Apache2: Removed packages and configuration
          ✅ Ephemeral Storage: Removed directory
          ✅ System: Cleaned up apt cache
          ========================================
          
          🧹 Cleanup completed successfully!
          The server has been restored to a clean state.
          ======================================== 