---
# Docker configuration
docker_user: "{{ ansible_user | default('ubuntu') }}"
docker_image: "louislam/uptime-kuma:latest"
docker_container_name: "uptime-kuma"
docker_host_port: "3001"
docker_container_port: "3001"
docker_volume_path: "/tmp/ephemeral-data"
docker_network_name: "web-network"
docker_restart_policy: "unless-stopped" 