# Non-sensitive variables
# This file contains non-sensitive configuration variables

# MySQL configuration
mysql_database: "webapp"
mysql_user: "webapp_user"
mysql_bind_address: "127.0.0.1"
mysql_skip_networking: false
mysql_root_password: "{{ vault_mysql_root_password }}"
mysql_user_password: "{{ vault_mysql_user_password }}"

# Docker configuration
docker_image: "louislam/uptime-kuma:latest"
docker_container_name: "uptime-kuma"
docker_host_port: "3001"
docker_container_port: "3001"
docker_network_name: "web-network"
docker_restart_policy: "unless-stopped"

# Apache2 configuration
apache2_web_root: "/var/www/html"
apache2_port: 80
apache2_security_headers: true
apache2_compression: true
apache2_caching: true

# Common configuration
ephemeral_volume_path: "/tmp/ephemeral-data" 