---
dependencies:
  - role: common
galaxy_info:
  author: Ansible Playbook
  description: MySQL database server installation and configuration
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - mysql
    - database
    - sql 