---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name:
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - unzip
      - wget
    state: present

- name: Create ephemeral storage directory
  file:
    path: "{{ ephemeral_volume_path | default('/tmp/ephemeral-data') }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user | default('ubuntu') }}"
    group: "{{ ansible_user | default('ubuntu') }}" 