---
dependencies: []
galaxy_info:
  author: Ansible Playbook
  description: Common tasks and packages for Ubuntu servers
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - common
    - ubuntu
    - system 