---
dependencies:
  - role: common
galaxy_info:
  author: Ansible Playbook
  description: Docker installation and container management
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - docker
    - containers
    - virtualization 